routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::group([
    'prefix' => 'admin',
], function () {
    // get login
    Route::get('/login',[App\Http\Controllers\Admin\LoginController::class, 'login'])->name('login');
    // post login
    Route::post('/login',[App\Http\Controllers\Admin\LoginController::class, 'doLogin'])->name('admin.login');

    Route::group([
        'middleware' => 'auth'
    ], function () {
        // dashboard
        Route::get('/',[App\Http\Controllers\Admin\DashboardController::class, 'index'])->name('dashboard.index');
        // logout
        Route::any('/logout',[App\Http\Controllers\Admin\LoginController::class, 'logout'])->name('admin.logout');
        // projects
        Route::resource('/projects',App\Http\Controllers\Admin\ProjectsController::class);
        // brands
        Route::resource('/brands',App\Http\Controllers\Admin\BrandsController::class);
        // categories
        Route::resource('/categories',App\Http\Controllers\Admin\CategoriesController::class);
        // contact us
        Route::get('/contact-us',[App\Http\Controllers\Admin\ContactUsController::class, 'index'])->name('admin.contact-us');
        // delete contact-us messages
        Route::delete('/contact-us/{id}',[App\Http\Controllers\Admin\ContactUsController::class, 'destroy'])->name('admin.contact-us.destroy');
    });
});

//Route::get('/',[App\Http\Controllers\Site\FileController::class, 'index'])->name('site.index');

//Route::get('/',[App\Http\Controllers\Site\ContactUsController::class, 'index'])->name('site.index');

Route::get('/',[App\Http\Controllers\Site\SiteController::class, 'index'])->name('site.index');

Route::get('/clients',[App\Http\Controllers\Site\SiteController::class, 'clients'])->name('clients.index');

Route::post('/clients',[App\Http\Controllers\Site\ContactUsController::class, 'store'])->name('contactUs.store');

Route::get('/increase-total-downloads',[App\Http\Controllers\Site\SettingsController::class, 'increaseTotalDownload'])->name('increase-total-downloads');

app/Models/Project.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Project extends Model
{
    use HasFactory;

    protected $fillable = [
        'title',
        'description',
        'photo',
        'category_id',
    ];

    public function category()
    {
        return $this->belongsTo(Category::class)->withDefault();
    }


    public function getPhotoAttribute()
    {
        return asset("uploads/projects/{$this->attributes['photo']}");
    }

}

app/Http/Controllers/Admin/ProjectsController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\ProjectsRequest;
use App\Http\Requests\UpdateProjectsRequest;
use App\Models\Category;
use App\Models\Project;
use Illuminate\Contracts\View\Factory;
use Illuminate\Contracts\View\View;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\Http\Response;

class ProjectsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return View
     */
    public function index(): View
    {
        $projects = Project::all();
        return view('projects.index', compact('projects'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return View
     */
    public function create(): View
    {
        $categories = Category::all();
        return view('projects.create', compact('categories'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param ProjectsRequest $request
     * @return RedirectResponse
     */
    public function store(ProjectsRequest $request)
    {
        $data = $request->validated();
        unset($data['photo']);
        if (request('photo')) {
            $this->storePhoto(request('photo'), 'projects');
            $data['photo'] = request('photo')->hashName();
        }
        Project::create($data);
        return redirect()->route('projects.index')->with('success', 'project add successfully');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param Project $project
     * @return Factory|View
     */
    public function edit(Project $project): View
    {
        $categories = Category::all();
        return view('projects.edit', compact('project', 'categories'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param UpdateProjectsRequest $request
     * @param Project $project
     * @return RedirectResponse
     */
    public function update(UpdateProjectsRequest $request, Project $project)
    {
        $data = $request->validated();
        unset($data['photo']);
        if (request('photo')) {
            $this->updatePhoto(request('photo'), $project->photo,  'projects');
            $data['photo'] = request('photo')->hashName();
        }
        $project->update($data);
        return redirect()->route('projects.index')->with('success', 'project updated successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  Project $project
     * @return RedirectResponse
     */
    public function destroy(Project $project)
    {
        $this->deletePhoto($project->photo, 'projects');
        $project->delete();
        return redirect()->route('projects.index')->with('success', 'project deleted successfully');
    }
}

resources/views/projects/create.blade.php
@extends('index')

@section('content')
    <section class="content d-flex align-items-center forms-section">
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-8 col-md-12 col-sm-12 px-0 m-auto">
                    <div class="card card-primary mb-0">
                        <!--    add new post form   -->
                        <form id="addPostForm" role="form" method="post" action="{{route('projects.store')}}" enctype="multipart/form-data">
                            @csrf
                            <div class="card-body">
                                <div class="row">
                                    <div class="form-group form-floating col-12 px-2">
                                        <label for="title">Project Title</label>
                                        <input type="text" id="title" name="title" class="form-control @error('title') is-invalid @enderror" value="{{old('title')}}" placeholder="Enter Project Title">
                                        @error('title')
                                            <div class="invalid-feedback">{{$message}}</div>
                                        @enderror
                                    </div>

                                    <div class="form-group form-floating col-12 px-2">
                                        <label for="client_id">Project Category</label>
                                        <select name="category_id" id="category_id" class="form-control @error('category_id') is-invalid @enderror">
                                            <option value="">choose category</option>
                                            @foreach($categories as $category)
                                                <option value="{{$category->id}}" {{old('category_id') == $category->id ? 'selected' : ''}}>{{$category->name}}</option>
                                            @endforeach
                                        </select>
                                        @error('category_id')
                                        <div class="invalid-feedback d-block">{{$message}}</div>
                                        @enderror
                                    </div>

                                    <div class="form-group">
                                        <label for="FormControlFile">project photo</label>
                                        <input type="file" name="photo" class="form-control-file" id="FormControlFile">
                                        @error('photo')
                                        <div style="color:#dc3545">the photo is required.</div>
{{--                                        <div class="invalid-feedback">{{$message}}</div>--}}
                                        @enderror
                                    </div>

                                </div>
                            </div>
                            <div class="card-footer text-center">
                                <button type="submit" id="submitFormBtn" class="btn btn-outline-blue">@lang('admin.submit')</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection

resources/views/projects/edit.blade.php
@extends('index')

@section('content')
    <section class="content d-flex align-items-center forms-section">
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-8 col-md-12 col-sm-12 px-0 m-auto">
                    <div class="card card-primary mb-0">
                        <!--    add new post form   -->
                        <form id="addPostForm" role="form" method="post" action="{{route('projects.update', $project->id)}}" enctype="multipart/form-data">
                            @csrf
                            @method('PUT')
                            <div class="card-body">
                                <div class="row">
                                    <div class="form-group form-floating col-12 px-2">
                                        <label for="title">Project Title</label>
                                        <input type="text" id="title" name="title" class="form-control @error('title') is-invalid @enderror" value="{{$project->title}}" placeholder="Enter Project Title">
                                        @error('title')
                                        <div class="invalid-feedback">{{$message}}</div>
                                        @enderror
                                    </div>

                                    <div class="form-group form-floating col-12 px-2">
                                        <label for="client_id">Project Category</label>
                                        <select name="category_id" id="category_id" class="form-control @error('category_id') is-invalid @enderror">
                                            <option value="">choose category</option>
                                            @foreach($categories as $category)
                                                <option value="{{$category->id}}" {{$project->category_id == $category->id ? 'selected' : ''}}>{{$category->name}}</option>
                                            @endforeach
                                        </select>
                                        @error('category_id')
                                        <div class="invalid-feedback d-block">{{$message}}</div>
                                        @enderror
                                    </div>

                                    <div class="form-group">
                                        <label for="exampleFormControlFile1">project photo</label>
                                        <input type="file" name="photo" value="{{$project->photo}}" class="form-control-file" id="exampleFormControlFile1">
                                    </div>
                                </div>
                                @error('photo')
                                <div style="color:#dc3545">the photo is required.</div>
                                <div class="invalid-feedback">{{$message}}</div>
                                @enderror
                            </div>
                            <div class="card-footer text-center">
                                <button type="submit" id="submitFormBtn" class="btn btn-outline-blue">@lang('admin.submit')</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection

resources/views/projects/index.blade.php
@extends('index')

@section('content')

    <div class="row" >
        <div class="container bg-light m-2">
            <div class="col-md-12 text-center">
                <a href="{{route('projects.create')}}" class="btn btn-outline-blue"><i class="fas fa-plus ms-1"></i> Add Project</a>
            </div>
        </div>

        <div class="col-12">
            <div class="card">
                @if(count($projects) > 0)
                    <table class="table">
                    <thead class="thead-dark">
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">Title</th>
                        <th scope="col">Category</th>
                        <th scope="col">Photo</th>
                        <th scope="col">Edit</th>
                        <th scope="col">Delete</th>
                    </tr>
                    </thead>
                    <tbody>
                    @foreach($projects as $index=>$project)
                        <tr>
                            <th scope="row">{{$index + 1}}</th>
                            <td>{{$project->title}}</td>
                            <td>{{$project->category->name}}</td>
                            <td><img class="img-thumbnail" style="width: 150px; height: 100px;"  src="{{$project->photo}}" alt=""></td>
                            <td>
                                <a href="{{route('projects.edit', $project->id)}}" class="btn btn-outline-blue"><i class="fas fa-edit ms-1"></i> </a>
                            </td>
                            <td>
                                <button type="button" class="btn btn-outline-danger" data-toggle="modal" data-target="#delete_group_{{$project->id}}"><i class="fas fa-trash  ms-1"></i></button>
                                <!-- delete modal-->
                                <div class="modal fade" id="delete_group_{{$project->id}}" tabindex="-1" role="dialog" aria-labelledby="delete_shipping" aria-hidden="true">
                                    <div class="modal-dialog" role="document">
                                        <div class="modal-content">
                                            <div class="modal-header">
                                                <h5 class="modal-title" id="exampleModalLabel">Delete Project</h5>
                                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                    <span aria-hidden="true">&times;</span>
                                                </button>
                                            </div>
                                            <div class="modal-body">
                                                Really need to delete  {{$project->title}}  !
                                            </div>
                                            <form method="post" action="{{route('projects.destroy',$project->id)}}">
                                                @csrf
                                                @method('DELETE')
                                                <div class="modal-footer">
                                                    <button type="button" class="btn btn-outline-dark" data-dismiss="modal">Cancel</button>
                                                    <button type="submit" class="btn btn-outline-danger">Delete</button>
                                                </div>
                                            </form>
                                        </div>
                                    </div>
                                </div>


                            </td>
                        </tr>
                    @endforeach
                    </tbody>
                </table>
                @endif
            </div>
        </div>
    </div>

@endsection