routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::group([
    'prefix' => 'admin',
], function () {
    // get login
    Route::get('/login',[App\Http\Controllers\Admin\LoginController::class, 'login'])->name('login');
    // post login
    Route::post('/login',[App\Http\Controllers\Admin\LoginController::class, 'doLogin'])->name('admin.login');

    Route::group([
        'middleware' => 'auth'
    ], function () {
        // dashboard
        Route::get('/',[App\Http\Controllers\Admin\DashboardController::class, 'index'])->name('dashboard.index');
        // logout
        Route::any('/logout',[App\Http\Controllers\Admin\LoginController::class, 'logout'])->name('admin.logout');
        // projects
        Route::resource('/projects',App\Http\Controllers\Admin\ProjectsController::class);
        // brands
        Route::resource('/brands',App\Http\Controllers\Admin\BrandsController::class);
        // categories
        Route::resource('/categories',App\Http\Controllers\Admin\CategoriesController::class);
        // contact us
        Route::get('/contact-us',[App\Http\Controllers\Admin\ContactUsController::class, 'index'])->name('admin.contact-us');
        // delete contact-us messages
        Route::delete('/contact-us/{id}',[App\Http\Controllers\Admin\ContactUsController::class, 'destroy'])->name('admin.contact-us.destroy');
    });
});

//Route::get('/',[App\Http\Controllers\Site\FileController::class, 'index'])->name('site.index');

//Route::get('/',[App\Http\Controllers\Site\ContactUsController::class, 'index'])->name('site.index');

Route::get('/',[App\Http\Controllers\Site\SiteController::class, 'index'])->name('site.index');

Route::get('/clients',[App\Http\Controllers\Site\SiteController::class, 'clients'])->name('clients.index');

Route::post('/clients',[App\Http\Controllers\Site\ContactUsController::class, 'store'])->name('contactUs.store');

Route::get('/increase-total-downloads',[App\Http\Controllers\Site\SettingsController::class, 'increaseTotalDownload'])->name('increase-total-downloads');

app/Http/Controllers/Admin/DashboardController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Brand;
use App\Models\Category;
use App\Models\ContactUs;
use App\Models\Project;
use App\Models\Setting;
use Illuminate\Contracts\View\View;

class DashboardController extends Controller
{
    /**
     * open login page.
     *
     * @return View
     */
    public function index(): View
    {
        $projectsCount = Project::count();
        $categoriesCount = Category::count();
        $brandsCount = Brand::count();
        $messagesCount = ContactUs::count();
        $totalDownloads = Setting::firstOrFail()->totalDownloads;
        return view('dashboard.index', compact('projectsCount', 'messagesCount', 'categoriesCount', 'brandsCount', 'totalDownloads'));
    }
}

resources/views/dashboard/index.blade.php
@extends('index')

@section('content')

    <!-- Main content -->
    <section class="content">
        <div class="container-fluid">
            <!-- Small boxes (Stat box) -->
            <div class="row">
                <div class="col-lg-3 col-6 p-1">
                    <!-- small box -->
                    <div class="small-box bg-info">
                        <div class="inner">
                            <h3>{{$categoriesCount}}</h3>
                            <p>Categories</p>
                        </div>
                        <div class="icon">
                            <i class="fas fa-folder"></i>
                        </div>
                        <a href="{{route('categories.index')}}" class="small-box-footer">@lang('admin.more_info') <i class="fas fa-arrow-circle-right"></i></a>
                    </div>
                </div>
                <div class="col-lg-3 col-6 p-1">
                    <!-- small box -->
                    <div class="small-box bg-info">
                        <div class="inner">
                            <h3>{{$projectsCount}}</h3>
                            <p>@lang('admin.new_projects')</p>
                        </div>
                        <div class="icon">
                            <i class="fas fa-project-diagram"></i>
                        </div>
                        <a href="{{route('projects.index')}}" class="small-box-footer">@lang('admin.more_info') <i class="fas fa-arrow-circle-right"></i></a>
                    </div>
                </div>

                <div class="col-lg-3 col-6 p-1">
                    <!-- small box -->
                    <div class="small-box bg-info">
                        <div class="inner">
                            <h3>{{$brandsCount}}</h3>
                            <p>Brands</p>
                        </div>
                        <div class="icon">
                            <i class="fab fa-artstation"></i>
                        </div>
                        <a href="{{route('brands.index')}}" class="small-box-footer">@lang('admin.more_info') <i class="fas fa-arrow-circle-right"></i></a>
                    </div>
                </div>

                <div class="col-lg-3 col-6 p-1">
                    <!-- small box -->
                    <div class="small-box bg-info">
                        <div class="inner">
                            <h3>{{$totalDownloads}}</h3>
                            <p>Total Downloads</p>
                        </div>
                        <div class="icon">
                            <i class="fas fa-download"></i>
                        </div>
                        <a href="#" class="small-box-footer"> <i class="fas fa-arrow-circle-rightw"></i></a>
                    </div>
                </div>

{{--                <div class="col-lg-3 col-6 p-1">--}}
{{--                    <!-- small box -->--}}
{{--                    <div class="small-box bg-info">--}}
{{--                        <div class="inner">--}}
{{--                            <h3>{{$messagesCount}}</h3>--}}
{{--                            <p>Contact Us</p>--}}
{{--                        </div>--}}
{{--                        <div class="icon">--}}
{{--                            <i class="fas fa-address-book"></i>--}}
{{--                        </div>--}}
{{--                        <a href="{{route('admin.contact-us')}}" class="small-box-footer">@lang('admin.more_info') <i class="fas fa-arrow-circle-right"></i></a>--}}
{{--                    </div>--}}
{{--                </div>--}}



            </div>
            <!-- /.row -->
        </div><!-- /.container-fluid -->
    </section>

@endsection