routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::group([
    'prefix' => 'admin',
], function () {
    // get login
    Route::get('/login',[App\Http\Controllers\Admin\LoginController::class, 'login'])->name('login');
    // post login
    Route::post('/login',[App\Http\Controllers\Admin\LoginController::class, 'doLogin'])->name('admin.login');

    Route::group([
        'middleware' => 'auth'
    ], function () {
        // dashboard
        Route::get('/',[App\Http\Controllers\Admin\DashboardController::class, 'index'])->name('dashboard.index');
        // logout
        Route::any('/logout',[App\Http\Controllers\Admin\LoginController::class, 'logout'])->name('admin.logout');
        // projects
        Route::resource('/projects',App\Http\Controllers\Admin\ProjectsController::class);
        // brands
        Route::resource('/brands',App\Http\Controllers\Admin\BrandsController::class);
        // categories
        Route::resource('/categories',App\Http\Controllers\Admin\CategoriesController::class);
        // contact us
        Route::get('/contact-us',[App\Http\Controllers\Admin\ContactUsController::class, 'index'])->name('admin.contact-us');
        // delete contact-us messages
        Route::delete('/contact-us/{id}',[App\Http\Controllers\Admin\ContactUsController::class, 'destroy'])->name('admin.contact-us.destroy');
    });
});

//Route::get('/',[App\Http\Controllers\Site\FileController::class, 'index'])->name('site.index');

//Route::get('/',[App\Http\Controllers\Site\ContactUsController::class, 'index'])->name('site.index');

Route::get('/',[App\Http\Controllers\Site\SiteController::class, 'index'])->name('site.index');

Route::get('/clients',[App\Http\Controllers\Site\SiteController::class, 'clients'])->name('clients.index');

Route::post('/clients',[App\Http\Controllers\Site\ContactUsController::class, 'store'])->name('contactUs.store');

Route::get('/increase-total-downloads',[App\Http\Controllers\Site\SettingsController::class, 'increaseTotalDownload'])->name('increase-total-downloads');

app/Models/Brand.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Brand extends Model
{
    use HasFactory;

    protected $fillable = [
        'title',
        'description',
        'photo',
    ];


    public function getPhotoAttribute()
    {
        return asset("uploads/brands/{$this->attributes['photo']}");
    }

}

app/Http/Controllers/Admin/BrandsController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\BrandsRequest;
use App\Http\Requests\ProjectsRequest;
use App\Http\Requests\UpdateBrandsRequest;
use App\Http\Requests\UpdateProjectsRequest;
use App\Models\Brand;
use App\Models\Project;
use Illuminate\Contracts\View\Factory;
use Illuminate\Contracts\View\View;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\Http\Response;

class BrandsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return View
     */
    public function index(): View
    {
        $brands = Brand::all();
        return view('brands.index', compact('brands'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return View
     */
    public function create(): View
    {
        return view('brands.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param BrandsRequest $request
     * @return RedirectResponse
     */
    public function store(BrandsRequest $request)
    {
        $data = $request->validated();
        unset($data['photo']);
        if (request('photo')) {
            $this->storePhoto(request('photo'), 'brands');
            $data['photo'] = request('photo')->hashName();
        }
        Brand::create($data);
        return redirect()->route('brands.index')->with('success', 'Brand add successfully');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param Brand $brand
     * @return Factory|View
     */
    public function edit(Brand $brand): View
    {
        return view('brands.edit', compact('brand'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param UpdateBrandsRequest $request
     * @param Brand $brand
     * @return RedirectResponse
     */
    public function update(UpdateBrandsRequest $request, Brand $brand)
    {
        $data = $request->validated();
        unset($data['photo']);
        if (request('photo')) {
            $this->updatePhoto(request('photo'), $brand->photo,  'brands');
            $data['photo'] = request('photo')->hashName();
        }
        $brand->update($data);
        return redirect()->route('brands.index')->with('success', 'Brand updated successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param Brand $brand
     * @return RedirectResponse
     */
    public function destroy(Brand $brand)
    {
        $this->deletePhoto($brand->photo, 'brands');
        $brand->delete();
        return redirect()->route('brands.index')->with('success', 'Brand deleted successfully');
    }
}

resources/views/brands/create.blade.php
@extends('index')

@section('content')
    <section class="content d-flex align-items-center forms-section">
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-8 col-md-12 col-sm-12 px-0 m-auto">
                    <div class="card card-primary mb-0">
                        <!--    add new post form   -->
                        <form id="addPostForm" role="form" method="post" action="{{route('brands.store')}}" enctype="multipart/form-data">
                            @csrf
                            <div class="card-body">
                                <div class="row">
                                    <div class="form-group form-floating col-12 px-2">
                                        <label for="title">Brand Title</label>
                                        <input type="text" id="title" name="title" class="form-control @error('title') is-invalid @enderror" value="{{old('title')}}" placeholder="Enter Brand Title">
                                        @error('title')
                                            <div class="invalid-feedback">{{$message}}</div>
                                        @enderror
                                    </div>

                                    <div class="form-group form-floating col-12 px-2">
                                        <label for="ticketDesc">Brand Description</label>
                                        <textarea rows="3" id="ticketDesc" name="description" class="form-control @error('description') is-invalid @enderror" placeholder="Enter Brand description">{{old('description')}}</textarea>
                                        @error('description')
                                        <div class="invalid-feedback d-block">{{$message}}</div>
                                        @enderror
                                    </div>

{{--                                    <div class="form-group form-floating col-12 px-2">--}}
{{--                                        <label for="title">Brand Description</label>--}}
{{--                                        <input type="text" id="title" name="description" class="form-control @error('title') is-invalid @enderror" value="{{old('description')}}" placeholder="Enter Brand description">--}}

{{--                                        @error('description')--}}
{{--                                            <div class="invalid-feedback">{{$message}}</div>--}}
{{--                                        @enderror--}}
{{--                                    </div>--}}


                                    <div class="form-group">
                                        <label for="FormControlFile">Brand photo</label>
                                        <input type="file" name="photo" class="form-control-file" id="FormControlFile">
                                        @error('photo')
                                        <div style="color:#dc3545">the photo is required.</div>
                                        @enderror
                                    </div>

                                </div>
                            </div>
                            <div class="card-footer text-center">
                                <button type="submit" id="submitFormBtn" class="btn btn-outline-blue">@lang('admin.submit')</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection

resources/views/brands/edit.blade.php
@extends('index')

@section('content')
    <section class="content d-flex align-items-center forms-section">
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-8 col-md-12 col-sm-12 px-0 m-auto">
                    <div class="card card-primary mb-0">
                        <!--    add new post form   -->
                        <form id="addPostForm" role="form" method="post" action="{{route('brands.update', $brand->id)}}" enctype="multipart/form-data">
                            @csrf
                            @method('PUT')
                            <div class="card-body">
                                <div class="row">
                                    <div class="form-group form-floating col-12 px-2">
                                        <label for="title">Brand Title</label>
                                        <input type="text" id="title" name="title" class="form-control @error('title') is-invalid @enderror" value="{{$brand->title}}" placeholder="Enter Brand Title">
                                        @error('title')
                                        <div class="invalid-feedback">{{$message}}</div>
                                        @enderror
                                    </div>

                                    <div class="form-group form-floating col-12 px-2">
                                        <label for="ticketDesc">Brand Description</label>
                                        <textarea rows="3" id="ticketDesc" name="description" class="form-control @error('description') is-invalid @enderror" placeholder="Enter Brand description">{{$brand->description}}</textarea>
                                        @error('description')
                                        <div class="invalid-feedback d-block">{{$message}}</div>
                                        @enderror
                                    </div>

                                    <div class="form-group">
                                        <label for="exampleFormControlFile1">Brand photo</label>
                                        <input type="file" name="photo" value="{{$brand->photo}}" class="form-control-file" id="exampleFormControlFile1">
                                    </div>
                                </div>
                                @error('photo')
                                <div style="color:#dc3545">the photo is required.</div>
                                <div class="invalid-feedback">{{$message}}</div>
                                @enderror
                            </div>
                            <div class="card-footer text-center">
                                <button type="submit" id="submitFormBtn" class="btn btn-outline-blue">@lang('admin.submit')</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection

resources/views/brands/index.blade.php
@extends('index')

@section('content')

    <div class="row" >
        <div class="container bg-light m-2">
            <div class="col-md-12 text-center">
                <a href="{{route('brands.create')}}" class="btn btn-outline-blue"><i class="fas fa-plus ms-1"></i> Add Brand</a>
            </div>
        </div>

        <div class="col-12">
            <div class="card">
                @if(count($brands) > 0)
                    <table class="table">
                    <thead class="thead-dark">
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">Title</th>
                        <th scope="col">Description</th>
                        <th scope="col">Photo</th>
                        <th scope="col">Edit</th>
                        <th scope="col">Delete</th>
                    </tr>
                    </thead>
                    <tbody>
                    @foreach($brands as $index=>$brand)
                        <tr>
                            <th scope="row">{{$index + 1}}</th>
                            <td>{{$brand->title}}</td>
                            <td>{{$brand->description}}</td>
                            <td><img class="img-thumbnail" width="150px" height="100px;" src="{{$brand->photo}}" alt=""></td>
                            <td>
                                <a href="{{route('brands.edit', $brand->id)}}" class="btn btn-outline-blue"><i class="fas fa-edit ms-1"></i> </a>
                            </td>
                            <td>
                                <button type="button" class="btn btn-outline-danger" data-toggle="modal" data-target="#delete_group_{{$brand->id}}"><i class="fas fa-trash  ms-1"></i></button>
                                <!-- delete modal-->
                                <div class="modal fade" id="delete_group_{{$brand->id}}" tabindex="-1" role="dialog" aria-labelledby="delete_shipping" aria-hidden="true">
                                    <div class="modal-dialog" role="document">
                                        <div class="modal-content">
                                            <div class="modal-header">
                                                <h5 class="modal-title" id="exampleModalLabel">Delete Brand</h5>
                                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                    <span aria-hidden="true">&times;</span>
                                                </button>
                                            </div>
                                            <div class="modal-body">
                                                Really need to delete  {{$brand->title}}  !
                                            </div>
                                            <form method="post" action="{{route('brands.destroy',$brand->id)}}">
                                                @csrf
                                                @method('DELETE')
                                                <div class="modal-footer">
                                                    <button type="button" class="btn btn-outline-dark" data-dismiss="modal">Cancel</button>
                                                    <button type="submit" class="btn btn-outline-danger">Delete</button>
                                                </div>
                                            </form>
                                        </div>
                                    </div>
                                </div>


                            </td>
                        </tr>
                    @endforeach
                    </tbody>
                </table>
                @endif
            </div>
        </div>
    </div>

@endsection